name: Conditional Environment Instance Variable


on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - staging 
      - dev

env:
  PROJECT_NAME: my-project
  REGION: europe-west1
  PROD_BRANCH: main
  STAGE_BRANCH: staging
  TEST_BRANCH: develop
  PROD_INSTANCE: prod
  STAGE_INSTANCE: stage
  TEST_INSTANCE: dev
    
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      instance: ${{ steps.set-variable.outputs.instance }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Instance variable
        id: set-variable
        run: |
          if [ ${{ github.ref }} == 'refs/heads/${{ env.PROD_BRANCH }}' ]; then
            echo "::set-output name=instance::${{ env.PROD_INSTANCE }}"
          elif [ ${{ github.ref }} == 'refs/heads/${{ env.STAGE_BRANCH }}' ]; then
            echo "::set-output name=instance::${{ env.STAGE_INSTANCE }}"
          elif [ ${{ github.ref }} == 'refs/heads/${{ env.TEST_BRANCH }}' ]; then
            echo "::set-output name=instance::${{ env.TEST_INSTANCE }}"
          else
            echo "::set-output name=instance::${{ github.ref }}"
          fi
        shell: bash
      - id: instance
        uses: ASzc/change-string-case-action@v2
        with:
          string: "${{ steps.set-variable.outputs.instance }}"
      - name: Read exported variable
        run: |
          echo "output: ${{ steps.set-variable.outputs.instance }}"
          echo "OUTPUT: ${{ steps.instance.outputs.uppercase }}"
          echo "::set-output name=instance_uppercase::${{ steps.instance.outputs.uppercase }}"
          
       
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - name: Read exported variable
        run: |
          echo "DEPLOY TO: ${{ env.PROJECT_NAME}}-${{needs.setup.outputs.instance}}-${{ env.REGION }}.domain.com"
          echo "INSTANCE: ${{ needs.setup.outputs.instance_uppercase }}"
          
