name: Conditional Environment Instance Variable
on:
  workflow_dispatch:
  push:

env:
  PROD_BRANCH: main
  STAGE_BRANCH: staging
  TEST_BRANCH: develop

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      instance: ${{ steps.set-variable.outputs.instance }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Instance variable
        id: set-variable
        run: |
          if [ ${{ github.ref }} == 'refs/heads/${{ env.PROD_BRANCH }}' ]; then
            echo "::set-output name=instance::prod"
          elif [ ${{ github.ref }} == 'refs/heads/${{ env.STAGE_BRANCH }}' ]; then
            echo "::set-output name=instance::stage"
          elif [ ${{ github.ref }} == 'refs/heads/${{ env.TEST_BRANCH }}' ]; then
            echo "::set-output name=instance::test"
          else
            echo "::set-output name=instance::${{ github.ref }}"
          fi
        shell: bash
      - name: Read exported variable
        run: |
          echo "OUTPUT: ${{ steps.setup.output.instance }}"
          if ${{ steps.setup.output.instance }} != prod; then
            echo "Game over!"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - name: Read exported variable
        run: |
          echo "OUTPUT: ${{needs.setup.outputs.instance}}"
